# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beacon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace_id', models.IntegerField(verbose_name='namespace id')),
                ('instance_id', models.IntegerField(verbose_name='instance id')),
                ('lat', models.FloatField(verbose_name='latitude')),
                ('lng', models.FloatField(verbose_name='longitude')),
                ('last_seen_timestamp', models.IntegerField(verbose_name='last seen timestamp')),
            ],
            options={
                'verbose_name': 'beacon',
                'verbose_name_plural': 'beacons',
            },
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50, verbose_name='user')),
                ('spot_timestamp', models.IntegerField(verbose_name='timestamp of spot')),
                ('lat', models.FloatField(verbose_name='latitude')),
                ('lng', models.FloatField(verbose_name='longitude')),
                ('beacon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='track.Beacon')),
            ],
            options={
                'verbose_name': 'spot',
                'verbose_name_plural': 'spots',
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('serial_number', models.IntegerField(primary_key=True, serialize=False, verbose_name='serial number')),
                ('is_beaconed', models.BooleanField(verbose_name='true if attached beacon confirmed')),
                ('is_live', models.BooleanField(verbose_name='true if vehicle is live')),
                ('beacon', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vehicle', to='track.Beacon')),
            ],
            options={
                'verbose_name': 'vehicle',
                'verbose_name_plural': 'vehicles',
            },
        ),
    ]
