# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 14:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beacon',
            name='instance_id',
            field=models.CharField(max_length=12, verbose_name='instance id'),
        ),
        migrations.AlterField(
            model_name='beacon',
            name='namespace_id',
            field=models.CharField(max_length=20, verbose_name='namespace id'),
        ),
    ]
