# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 07:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0003_auto_20151217_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='is_beaconed',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='is_live',
        ),
    ]
