# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-21 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0004_auto_20151221_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon',
            name='is_live',
            field=models.BooleanField(default=False, verbose_name='true if beacon is live'),
        ),
    ]
