# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-06 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0005_beacon_is_live'),
    ]

    operations = [
        migrations.AddField(
            model_name='beacon',
            name='registration_number',
            field=models.CharField(max_length=30, null=True, verbose_name='registration number associated with beacon'),
        ),
    ]
