# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-01-07 15:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0006_beacon_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='route_name',
            field=models.CharField(max_length=20, null=True, verbose_name='route name'),
        ),
    ]
